#
# Probe descriptions.
#
vars:
  _probes.commonPath: /opt/rainbow/targets/znews-ss/system/probes
probes:

  LoadProbe0:
    alias: load
    location: "${customize.system.target.lb}"
    type: script
    scriptInfo:
      mode: continual
      path: "${_probes.commonPath}/loadProbe.pl"
      argument: "-o load.out"

  LoadProbe1:
    alias: load
    location: "${customize.system.target.web0}"
    type: script
    scriptInfo:
      mode: continual
      path: "${_probes.commonPath}/loadProbe.pl"
      argument: "-o load.out"

  LoadProbe2:
    alias: load
    location: "${customize.system.target.web1}"
    type: script
    scriptInfo:
      mode: continual
      path: "${_probes.commonPath}/loadProbe.pl"
      argument: "-o load.out"

  LoadProbe3:
    alias: load
    location: "${customize.system.target.web2}"
    type: script
    scriptInfo:
      mode: continual
      path: "${_probes.commonPath}/loadProbe.pl"
      argument: "-o load.out"

  ClientProxyProbe0:
    alias: clientproxy
    location: "${customize.system.target.master}"
    type: java
    javaInfo:
      class: org.sa.rainbow.translator.znn.probes.ClientProxyProbe
      period: 2000
      args.length: 1
      args.0: "http://${customize.system.target.lb}:1081/news.php"
